services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: kirayadoor-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - kirayadoor-sqlserver-data:/var/opt/mssql

volumes:
  kirayadoor-sqlserver-data:

